name: CI caller

on:
  push:
    branches: [ $default-branch ]
    paths-ignore: [ cmake/modcam_version.cmake ]
  pull_request:
    paths-ignore: [ cmake/modcam_version.cmake ]

jobs:
  ci:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        cpp_compiler: [g++, clang++, cl]
        exclude:
          - os: windows-latest
            cpp_compiler: g++
          - os: windows-latest
            cpp_compiler: clang++
          - os: ubuntu-latest
            cpp_compiler: cl
    uses: ./.github/workflows/ci.yml
    with:
      os: ${{ matrix.os }}
      build_type: ${{ matrix.build_type }}
      cpp_compiler: ${{ matrix.cpp_compiler }}
